# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "51e3614095aef0c998e3cceb94194634"
application_url = "https://example.com/"
embedded = true
name = "kawan-code-app"
handle = "kawan-code-app"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false
